### ISSUE TITLE
Nothing happens when I run

### ISSUE THREAD

**Issue by MrYossu** [captainsafia/blazoract#25]
Hello,

I was watching the talk on the dev conference, and wanted to play with this code. I had a lot of trouble getting it to compile, as VS couldn't download some of the Nuget packages. I removed them and added the RC version in, and now it compiles. However, when I try to run it, I get a plain white browser window with the word "Loading..." at the top left. Nothing happens after that.

Anyone any ideas? Thanks

**Comment by captainsafia** [comment]
I've updated to the RTM versions in #26 and confirmed that it works.

I would recommend running a `dotnet clean` before building and running the project again.
